variables:
  DOCKER_HOST: "tcp://localhost:2375"
  DOCKER_DRIVER: overlay2
  CXXFLAGS: "-Wno-error"
  CFLAGS: "-Wno-error"

stages:
  - build

build-spl-files:
  stage: build
  image:
    name: eu.gcr.io/coral-muse-571/alpine_ci_k8s:latest
  services:
    - docker:dind
  dependencies: []
  script:
    - CONTAINER_ID=$(docker run -d -p 8000:8000 -e 'SPLUNK_START_ARGS=--accept-license' -e 'SPLUNK_PASSWORD=admin123' splunk/splunk:latest start)
    - sleep 60
    - docker exec -u 0 $CONTAINER_ID ls /opt/splunk/etc/apps
    - docker cp src/Egnyte_Protect $CONTAINER_ID:/opt/splunk/etc/apps
    - docker exec -u 0 $CONTAINER_ID chown -R splunk:splunk /opt/splunk/etc/apps/Egnyte_Protect
    - docker exec -u 0 $CONTAINER_ID chmod -R 644 /opt/splunk/etc/apps/Egnyte_Protect/
    - docker exec -u 0 $CONTAINER_ID chmod 700 /opt/splunk/etc/apps/Egnyte_Protect/default
    - docker exec -u 0 $CONTAINER_ID chmod 700 /opt/splunk/etc/apps/Egnyte_Protect/metadata
    - docker exec -u 0 $CONTAINER_ID chmod 700 /opt/splunk/etc/apps/Egnyte_Protect/static
    - docker exec -u 0 $CONTAINER_ID chmod 700 /opt/splunk/etc/apps/Egnyte_Protect/default/data
    - docker exec -u 0 $CONTAINER_ID chmod 700 /opt/splunk/etc/apps/Egnyte_Protect/default/data/ui
    - docker exec -u 0 $CONTAINER_ID chmod 700 /opt/splunk/etc/apps/Egnyte_Protect/default/data/ui/views
    - docker exec -u 0 $CONTAINER_ID chmod 700 /opt/splunk/etc/apps/Egnyte_Protect/default/data/ui/nav
    - docker exec -u 0 $CONTAINER_ID tar cvf /opt/splunk/etc/apps/Egnyte_Protect.tar /opt/splunk/etc/apps/Egnyte_Protect
    - docker exec -u 0 $CONTAINER_ID gzip /opt/splunk/etc/apps/Egnyte_Protect.tar

    - docker cp src/TA-egnyte-protect $CONTAINER_ID:/opt/splunk/etc/apps
    - docker exec -u 0 $CONTAINER_ID chown -R splunk:splunk /opt/splunk/etc/apps/TA-egnyte-protect
    - docker exec -u 0 $CONTAINER_ID chmod -R 644 /opt/splunk/etc/apps/TA-egnyte-protect/
    - docker exec -u 0 $CONTAINER_ID chmod -R 755 /opt/splunk/etc/apps/TA-egnyte-protect/bin
    - docker exec -u 0 $CONTAINER_ID chmod 700 /opt/splunk/etc/apps/TA-egnyte-protect/default
    - docker exec -u 0 $CONTAINER_ID chmod 700 /opt/splunk/etc/apps/TA-egnyte-protect/default/data
    - docker exec -u 0 $CONTAINER_ID chmod 700 /opt/splunk/etc/apps/TA-egnyte-protect/default/data/ui
    - docker exec -u 0 $CONTAINER_ID chmod 700 /opt/splunk/etc/apps/TA-egnyte-protect/default/data/ui/nav
    - docker exec -u 0 $CONTAINER_ID chmod 700 /opt/splunk/etc/apps/TA-egnyte-protect/default/data/ui/views
    - docker exec -u 0 $CONTAINER_ID chmod 700 /opt/splunk/etc/apps/TA-egnyte-protect/metadata
    - docker exec -u 0 $CONTAINER_ID chmod 700 /opt/splunk/etc/apps/TA-egnyte-protect/static
    - docker exec -u 0 $CONTAINER_ID chmod 700 /opt/splunk/etc/apps/TA-egnyte-protect/appserver
    - docker exec -u 0 $CONTAINER_ID chmod 700 /opt/splunk/etc/apps/TA-egnyte-protect/appserver/static
    - docker exec -u 0 $CONTAINER_ID chmod 700 /opt/splunk/etc/apps/TA-egnyte-protect/appserver/static/css
    - docker exec -u 0 $CONTAINER_ID chmod 700 /opt/splunk/etc/apps/TA-egnyte-protect/appserver/static/img
    - docker exec -u 0 $CONTAINER_ID chmod 700 /opt/splunk/etc/apps/TA-egnyte-protect/appserver/static/js
    - docker exec -u 0 $CONTAINER_ID chmod 700 /opt/splunk/etc/apps/TA-egnyte-protect/appserver/templates
    - docker exec -u 0 $CONTAINER_ID tar cvf /opt/splunk/etc/apps/TA-egnyte-protect.tar /opt/splunk/etc/apps/TA-egnyte-protect
    - docker exec -u 0 $CONTAINER_ID gzip /opt/splunk/etc/apps/TA-egnyte-protect.tar

    - mkdir builds
    - docker cp $CONTAINER_ID:/opt/splunk/etc/apps/Egnyte_Protect.tar.gz builds/Egnyte_Protect.spl
    - docker cp $CONTAINER_ID:/opt/splunk/etc/apps/TA-egnyte-protect.tar.gz builds/TA-egnyte-protect.spl
  artifacts:
    paths:
      - builds
    expire_in: 1 week