variables:
  DOCKER_HOST: "tcp://localhost:2375"
  DOCKER_DRIVER: overlay2
  CXXFLAGS: "-Wno-error"
  CFLAGS: "-Wno-error"
  CURRENT_NODE_ALPINE: "alpine:3.7"
  DOCKER_WRITER_GCR_JSON_BASE64: "${DOCKER_WRITER_PINT_PROTECT_GCR_JSON_BASE64}"
  GCR_CONTAINER_REGISTRY_NAME: "egnyteprotect-automation"
  SSH_PRIVATE_KEY_BASE64: ${SSH_PINT_CI_PRIVATE_KEY_BASE64}
  SSH_CONFIG: "Host *\n\tStrictHostKeyChecking no\n\n"

stages:
  - build

build-spl-files:
  stage: build
  image:
    name: splunk/splunk:latest
    entrypoint: ["/bin/bash", "/sbin/entrypoint.sh", "start-service"]
  dependencies: []
  script:
    - cd src
    - ls -la /opt/splunk/etc
    - sudo mkdir /opt/splunk/etc/apps
    - sudo cp -R . /opt/splunk/etc/apps
    - sudo chown -R splunk:splunk /opt/splunk/etc/apps/TA-egnyte-protect
    - sudo chown -R splunk:splunk /opt/splunk/etc/apps/Egnyte_Protect
    - cd /opt/splunk/bin
    - ls -la
    - ./splunk package app Egnyte_Protect
    - ./splunk package app TA-egnyte-protect
  artifacts:
    paths:
      - /opt/splunk/etc/system/static/app-packages/