variables:
  DOCKER_HOST: "tcp://localhost:2375"
  DOCKER_DRIVER: overlay2
  CXXFLAGS: "-Wno-error"
  CFLAGS: "-Wno-error"

stages:
  - build

build-spl-files:
  stage: build
  image:
    name: eu.gcr.io/coral-muse-571/alpine_ci_k8s:latest
  services:
    - docker:dind
  dependencies: []
  script:
    - CONTAINER_ID=$(docker run -d -p 8000:8000 -e 'SPLUNK_START_ARGS=--accept-license' -e 'SPLUNK_PASSWORD=admin123' splunk/splunk:latest start)
    - sleep 60
    - docker exec -u 0 $CONTAINER_ID ls /opt/splunk/etc/apps
    - docker cp src/Egnyte_Protect $CONTAINER_ID:/opt/splunk/etc/apps
    - docker cp src/TA-egnyte-protect $CONTAINER_ID:/opt/splunk/etc/apps
    - docker exec -u 0 $CONTAINER_ID chown -R splunk:splunk /opt/splunk/etc/apps/Egnyte_Protect
    - docker exec -u 0 $CONTAINER_ID chmod +R 644 /opt/splunk/etc/apps/Egnyte_Protect/default
    - docker exec -u 0 $CONTAINER_ID chmod +R 644 /opt/splunk/etc/apps/Egnyte_Protect/metadata
    - docker exec -u 0 $CONTAINER_ID chmod +R 644 /opt/splunk/etc/apps/Egnyte_Protect/static
    - docker exec -u 0 $CONTAINER_ID chmod +R 644 /opt/splunk/etc/apps/Egnyte_Protect/README.md
    - docker exec -u 0 $CONTAINER_ID chown -R splunk:splunk /opt/splunk/etc/apps/TA-egnyte-protect
    - docker exec -u 0 $CONTAINER_ID /opt/splunk/bin/splunk package app Egnyte_Protect -auth admin:admin123
    - docker exec -u 0 $CONTAINER_ID /opt/splunk/bin/splunk package app TA-egnyte-protect -auth admin:admin123
    - mkdir builds
    - APP_VERSION=$(docker exec -u 0 $CONTAINER_ID cat /opt/splunk/etc/apps/Egnyte_Protect/default/app.conf | grep version | sed 's/^version[[:blank:]]*=[[:blank:]]*\([0-9]*\.[0-9]*\.[0-9]*\).*$/\1/')
    - docker cp $CONTAINER_ID:/opt/splunk/etc/system/static/app-packages/Egnyte_Protect.spl builds/Egnyte_Protect-$APP_VERSION.spl
    - ADDON_VERSION=$(docker exec -u 0 $CONTAINER_ID cat /opt/splunk/etc/apps/TA-egnyte-protect/default/app.conf | grep version | sed 's/^version[[:blank:]]*=[[:blank:]]*\([0-9]*\.[0-9]*\.[0-9]*\).*$/\1/')
    - docker cp $CONTAINER_ID:/opt/splunk/etc/system/static/app-packages/TA-egnyte-protect.spl builds/TA-egnyte-protect-$ADDON_VERSION.spl
  artifacts:
    paths:
      - builds
    expire_in: 1 week