variables:
  DOCKER_HOST: "tcp://localhost:2375"
  DOCKER_DRIVER: overlay2
  CXXFLAGS: "-Wno-error"
  CFLAGS: "-Wno-error"
  CURRENT_NODE_ALPINE: "alpine:3.7"
  DOCKER_WRITER_GCR_JSON_BASE64: "${DOCKER_WRITER_PINT_PROTECT_GCR_JSON_BASE64}"
  GCR_CONTAINER_REGISTRY_NAME: "egnyteprotect-automation"
  SSH_PRIVATE_KEY_BASE64: ${SSH_PINT_CI_PRIVATE_KEY_BASE64}
  SSH_CONFIG: "Host *\n\tStrictHostKeyChecking no\n\n"

stages:
  - build

build-spl-files:
  stage: build
  image:
    name: eu.gcr.io/coral-muse-571/alpine_ci_k8s:latest
  services:
    - docker:dind
  dependencies: []
  script:
    - CONTAINER_ID=$(docker run -d -p 8000:8000 -e 'SPLUNK_START_ARGS=--accept-license' -e 'SPLUNK_PASSWORD=admin123' splunk/splunk:latest start)
    - docker exec -it CONTAINER_ID /bin/bash
    - ls -la
