variables:
  DOCKER_HOST: "tcp://localhost:2375"
  DOCKER_DRIVER: overlay2
  CXXFLAGS: "-Wno-error"
  CFLAGS: "-Wno-error"

stages:
  - build

build-spl-files:
  stage: build
  image:
    name: eu.gcr.io/coral-muse-571/alpine_ci_k8s:latest
  services:
    - docker:dind
  dependencies: []
  script:
    - CONTAINER_ID=$(docker run -d -p 8000:8000 -e 'SPLUNK_START_ARGS=--accept-license' -e 'SPLUNK_PASSWORD=admin123' splunk/splunk:latest start)
    - sleep 60
    - docker cp /integrations/splunk-protect/src/Egnyte_Protect $CONTAINER_ID:/opt/splunk/etc/apps
    - docker cp /integrations/splunk-protect/src/TA-egnyte-protect $CONTAINER_ID:/opt/splunk/etc/apps
    - docker exec -u 0 $CONTAINER_ID chown -R splunk:splunk /opt/splunk/etc/apps/Egnyte_Protect
    - docker exec -u 0 $CONTAINER_ID chown -R splunk:splunk /opt/splunk/etc/apps/TA-egnyte-protect
    - docker exec -u 0 $CONTAINER_ID /opt/splunk/bin/splunk package app Egnyte_Protect -auth admin:admin123
    - docker exec -u 0 $CONTAINER_ID /opt/splunk/bin/splunk package app TA-egnyte-protect -auth admin:admin123
    - mkdir /integrations/splunk-protect/builds
    - docker cp $CONTAINER_ID:/opt/splunk/etc/system/static/app-packages/Egnyte_Protect.spl /integrations/splunk-protect/builds
    - docker cp $CONTAINER_ID:/opt/splunk/etc/system/static/app-packages/TA-egnyte-protect.spl /integrations/splunk-protect/builds
  artifacts:
    paths:
      - /integrations/splunk-protect/builds
    expire_in: 1 week
  