variables:
  DOCKER_HOST: "tcp://localhost:2375"
  DOCKER_DRIVER: overlay2
  CXXFLAGS: "-Wno-error"
  CFLAGS: "-Wno-error"

stages:
  - build

build-spl-files:
  stage: build
  image:
    name: eu.gcr.io/coral-muse-571/alpine_ci_k8s:latest
  dependencies: []
  script:
    - cd src/Egnyte_Protect
    - chmod -R 644 *
    - chmod 700 default
    - chmod 700 metadata
    - chmod 700 static
    - chmod 700 default/data
    - chmod 700 default/data/ui
    - chmod 700 default/data/ui/views
    - chmod 700 default/data/ui/nav
    - cd ..
    - tar cvf Egnyte_Protect.tar Egnyte_Protect
    - gzip Egnyte_Protect.tar

    - cd TA-egnyte-protect
    - chmod -R 644 *
    - chmod -R 755 bin
    - chmod 700 default
    - chmod 700 default/data
    - chmod 700 default/data/ui
    - chmod 700 default/data/ui/nav
    - chmod 700 default/data/ui/views
    - chmod 700 metadata
    - chmod 700 static
    - chmod 700 appserver
    - chmod 700 appserver/static
    - chmod 700 appserver/static/css
    - chmod 700 appserver/static/img
    - chmod 700 appserver/static/js
    - chmod 700 appserver/templates
    - cd ..
    - tar cvf TA-egnyte-protect.tar TA-egnyte-protect
    - gzip TA-egnyte-protect.tar

    - cd ..
    - mkdir builds
    - cp src/Egnyte_Protect.tar.gz builds/Egnyte_Protect.spl
    - cp src/TA-egnyte-protect.tar.gz builds/TA-egnyte-protect.spl
  artifacts:
    paths:
      - builds
    expire_in: 1 week